// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyGPuz5Xi_sRmQH_Ni4iq3l7ns1vIaI20',
    appId: '1:44213832273:web:3c46603acb197e436bc670',
    messagingSenderId: '44213832273',
    projectId: 'marker-39904',
    authDomain: 'marker-39904.firebaseapp.com',
    storageBucket: 'marker-39904.firebasestorage.app',
    measurementId: 'G-NF80GNP6JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgpe7Vg3ktzj4x1cLgy1wVqVs00rvctKw',
    appId: '1:44213832273:android:a92420267a841b126bc670',
    messagingSenderId: '44213832273',
    projectId: 'marker-39904',
    storageBucket: 'marker-39904.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOXWtPoDiHvpbrAMKffhIAWmjkp4HPAJ8',
    appId: '1:44213832273:ios:ee0001a771a97aac6bc670',
    messagingSenderId: '44213832273',
    projectId: 'marker-39904',
    storageBucket: 'marker-39904.firebasestorage.app',
    iosBundleId: 'com.kmtemp.marker.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOXWtPoDiHvpbrAMKffhIAWmjkp4HPAJ8',
    appId: '1:44213832273:ios:5aafe6e200ebbe296bc670',
    messagingSenderId: '44213832273',
    projectId: 'marker-39904',
    storageBucket: 'marker-39904.firebasestorage.app',
    iosBundleId: 'com.kmtemp.marker.app.marker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyGPuz5Xi_sRmQH_Ni4iq3l7ns1vIaI20',
    appId: '1:44213832273:web:677a1ba052f6cdaf6bc670',
    messagingSenderId: '44213832273',
    projectId: 'marker-39904',
    authDomain: 'marker-39904.firebaseapp.com',
    storageBucket: 'marker-39904.firebasestorage.app',
    measurementId: 'G-X6WPFGCQDP',
  );
}
